env:
  browser: false
  es2021: true
extends: standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  {
    'semi': 'off',
    '@typescript-eslint/semi': 'off',
    '@typescript-eslint/space-before-function-paren': 'off',
    '@typescript-eslint/explicit-function-return-type': 'off',
    '@typescript-eslint/member-delimiter-style': 'off',
    '@typescript-eslint/strict-boolean-expressions':'off',
    '@typescript-eslint/no-extraneous-class':'off',
    '@typescript-eslint/no-unused-vars':'off',
    '@typescript-eslint/no-useless-constructor':'off'
  }
